### ISSUE TITLE
請問 Luna 模塊中的 clan_battle/period_ranking 所用的 request 內容要怎麼取得?

### ISSUE THREAD

**Issue by sd016808** [infinityedge01/qqbot2#1]
你好，目前打算將Luna的功能應用到台服，請問以下的 request 內容該如何正確填寫或取得？
{'clan_id': 6770, 'clan_battle_id': -1, 'period': -1, 'month': 0, 'page': page, 'is_my_clan': 0, 'is_first': 1}

如果都不改直接送，會得到錯誤訊息如下：{'status': 3, 'title': '伺服器錯誤', 'message': '目前未隸屬於戰隊。\\n即將返回標題畫面。'}

根據這個錯誤訊息，我猜是request的封包內容不對，我確定我登入的帳號(UDID、VIEWER)是有加入戰隊的。

方便的話可以告知小弟該如何得到這幾個欄位的正確資訊嗎?

**Comment by infinityedge01** [comment]
clan_id 内容需要在安卓模擬器中使用抓包軟體（如HTTPCanary）在登入客戶端查詢戰隊排名后得到。
其它内容不需要改變。

**Comment by sd016808** [comment]
你好，我使用HTTPCanary或是Fiddler等抓包軟體去抓封包時，發現只要開啟抓包的功能後，公主連結就無法登入，錯誤畫面如下：
![image](https://user-images.githubusercontent.com/9477727/124076393-c589b880-da78-11eb-8f17-8f42dbbdaa0a.png)

HTTPCanary是有偵測到公連的request封包的，但遊戲無法登入，如下圖：
![image](https://user-images.githubusercontent.com/9477727/124076555-008bec00-da79-11eb-8d91-7d734036f273.png)
![image](https://user-images.githubusercontent.com/9477727/124077062-a0497a00-da79-11eb-8156-a73ecd459915.png)

憑證的部分我有安裝了，也沒有打開Root功能，請問您有遇到類似的狀況嗎？
我使用的模擬器為雷電模擬器 4.0，內建的Android版本為7.1版

**Comment by sd016808** [comment]
你好，我後來先不打開抓包軟體，我先打開公主連結的遊戲，等到我切換到戰隊戰分頁時才打開抓包軟體，這樣子可以取得request的封包，但沒辦法取得response的部分。

如果有response封包我就可以透過Luna 模塊裡面的 unpack 去拿到 AES Key，再進而對 request 裡面的 Data 做解密的動作拿到cland_id，但我目前抓包軟體拿不到response，我有辦法直接針對 request 的部分直接解密嗎？

下圖是抓包軟體抓到的request封包：
![image](https://user-images.githubusercontent.com/9477727/124091861-d8a48480-da88-11eb-820f-04536ae0482e.png)
![image](https://user-images.githubusercontent.com/9477727/124091936-eb1ebe00-da88-11eb-9da7-d03f6ef8f220.png)

我有試著直接把 request 的 data 直接丟到 Luna 的 unpack 函式，但沒辦法成功解密，如下圖：
![image](https://user-images.githubusercontent.com/9477727/124092233-35a03a80-da89-11eb-81ee-a85dc2b49f6b.png)

**Comment by infinityedge01** [comment]
只需抓到request封包即可，需要的 clan_id 即在此處。
台服的加密解密方式同B服不同，不能使用Luna中對應模塊進行加密解密。

**Comment by sd016808** [comment]
你好，方便的話可以提示一下我哪邊解密錯了嗎？
我確認我目前request加密的流程是正確的，有成功取回過別的API的response，例如競技場的資料。
但我按照加密的方式逆向解密request封包，始終沒辦法正確還原。

```python
# 這是request加密的部分
def pack(self, data: object, key: bytes) -> tuple:
    aes = AES.new(key, AES.MODE_CBC, self._getiv())
    packed = packb(data,
        use_bin_type = False
    )
    return packed, aes.encrypt(pad(packed, 16)) + key

# 這是嘗試還原加密的request
def unpack(data: bytes):
    key = data[-32:]  # key的長度為32個 bytes
    data = data[:-32]
    data = b"\0" + data #長度159不是16的倍數補0
    aes = AES.new(key, AES.MODE_CBC, iv = _getiv()) #_getiv使用 UDID 轉換而來
    dec = aes.decrypt(data) 
    dec = unpad(dec, 16)
    return unpackb(dec) # msgpack.exceptions.ExtraData: unpack(b) received extra data. 這裡會報錯
```

**Comment by sd016808** [comment]
我發現我是白癡，我封包少複製了一個byte，根本不用補零，改了之後甚麼都對了ORZ
感謝大大的教學
